quarkus.application.name=quarkus-template
quarkus.http.port=${HTTP_PORT:8080}

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, spanId=%X{spanId} [%c{2.}] (%t) %s%e%n

# HTTP access log configuration
quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b "%{i,Referer}" \
  "%{i,User-Agent}" traceId=%X{traceId} spanId=%X{spanId}

quarkus.otel.enabled=true
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=false
quarkus.otel.logs.enabled=false
quarkus.otel.sdk.disabled=${QUARKUS_OTEL_SDK_DISABLED:true}
quarkus.otel.exporter.otlp.enabled=true
quarkus.otel.exporter.otlp.endpoint=${QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
quarkus.otel.service.name=${DD_SERVICE:${quarkus.application.name}}
quarkus.otel.resource.attributes=deployment.environment=${DD_ENV:local},service.version=${DD_VERSION:1.0.0-SNAPSHOT}

%dev.quarkus.smallrye-graphql.ui.always-include=true
%test.quarkus.smallrye-graphql.ui.always-include=true
%dev.quarkus.swagger-ui.always-include=true
%test.quarkus.swagger-ui.always-include=true
